import { test, expect } from '@playwright/test';

test('task, project, and goal workflow persists and renders safely', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Today.' })).toBeVisible();
  await page.getByRole('button', { name: 'Try sample tasks' }).click();
  await expect(page.getByText('Sketch ideas for the homepage', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'New project', exact: true }).first().click();
  await page.getByLabel('Project name').fill('Test project');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'My goals' }).click();
  await page.getByRole('button', { name: 'New goal', exact: true }).click();
  await page.getByLabel('Your goal').fill('Ship the project');
  await page.getByLabel('Why it matters').fill('A clear milestone.');
  await page.getByRole('button', { name: 'Create goal', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Add task', exact: true }).first().click();
  const taskTitle = '<img src=x onerror=alert(1)> Write 100%';
  await page.getByLabel('What would you like to do?').fill(taskTitle);
  await page.getByLabel('Notes', { exact: false }).fill('Saved notes');
  await page.getByLabel('Project', { exact: true }).selectOption({ label: 'Test project' });
  await page.getByLabel('Linked goal').selectOption({ label: 'Ship the project' });
  await page.getByLabel('Priority', { exact: true }).selectOption('high');
  await page.getByRole('dialog').getByRole('button', { name: 'Add task' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: /Test project/ }).click();
  await expect(page.getByText(taskTitle, { exact: true })).toBeVisible();
  await expect(page.locator('.task-row img')).toHaveCount(0);
  await page.reload();
  await expect(page.getByText(taskTitle, { exact: true })).toBeVisible();
  await page.getByRole('button', { name: `Edit ${taskTitle}`, exact: true }).click();
  await expect(page.getByLabel('Notes')).toHaveValue('Saved notes');
  await page.getByLabel('What would you like to do?').fill('Revised 100% task');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Complete Revised 100% task', exact: true }).click();
  await expect(page.getByText('Revised 100% task', { exact: true })).not.toBeVisible();
  await page.getByRole('button', { name: 'My goals' }).click();
  await expect(page.locator('.goal-card').filter({ hasText: 'Ship the project' })).toContainText('100%');
  await page.getByRole('button', { name: /Find a task/ }).click();
  await page.getByPlaceholder('Search task titles and notes…').fill('100%');
  await expect(page.getByText('Revised 100% task', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit Revised 100% task', exact: true }).click();
  await page.getByRole('button', { name: 'Delete task', exact: true }).click();
  await page.getByRole('button', { name: 'Delete task', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByText('Revised 100% task', { exact: true })).not.toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile navigation, focus timer, and keyboard task entry work', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Today.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: /Upcoming/ }).click();
  await expect(page.getByRole('heading', { name: 'Upcoming.' })).toBeVisible();
  await expect(page.locator('#scrim')).not.toBeVisible();
  await page.getByRole('button', { name: 'Start a 25 min focus' }).click();
  await expect(page.getByRole('button', { name: 'Pause focus' })).toBeVisible();
  await expect(page.locator('#timer')).not.toHaveText('25:00');
  await page.getByRole('button', { name: 'Pause focus' }).click();
  await page.getByRole('button', { name: 'Reset timer' }).click();
  await expect(page.locator('#timer')).toHaveText('25:00');
  await page.keyboard.press('n');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
});

test('API rejects invalid requests, protects conflicts, and exports persisted data', async ({ request }) => {
  const invalid = await request.post('/api/tasks', { data: { title: 'Invalid', due_date: '2026-02-30' } });
  expect(invalid.status()).toBe(400);
  const crossSite = await request.post('/api/tasks', { data: { title: 'Blocked' }, headers: { Origin: 'https://example.com' } });
  expect(crossSite.status()).toBe(403);
  const created = await request.post('/api/tasks', { data: { title: 'API durability', priority: 'high' } });
  expect(created.status()).toBe(201); const task = await created.json();
  const update = await request.patch(`/api/tasks/${task.id}`, { data: { revision: task.revision, title: 'Updated via API' } });
  expect(update.status()).toBe(200);
  const stale = await request.patch(`/api/tasks/${task.id}`, { data: { revision: task.revision, title: 'Stale edit' } });
  expect(stale.status()).toBe(409);
  const exported = await request.get('/api/export'); expect(exported.status()).toBe(200);
  expect((await exported.json()).tasks.some(t => t.title === 'Updated via API')).toBe(true);
  const oversized = await request.post('/api/tasks', { data: { title: 'Too much', notes: 'x'.repeat(40000) } });
  expect(oversized.status()).toBe(413);
});
